---
version: 2
jobs:
  build:
    docker:
      - image: docker:18-git
    environment:
      IMAGE_ID: jessestuart/vagrant-build-base

    steps:
      - checkout
      - setup_remote_docker

      - run:
          name: Authenticate with Docker Hub.
          command: |
            docker login -u $DOCKERHUB_USER -p $DOCKERHUB_PASS

      - run:
          name: Build Docker image.
          command: |
            docker build -t "${IMAGE_ID}" .

      - run:
          name: Push image to Docker Hub.
          command: |
            docker tag    "${IMAGE_ID}" "${IMAGE_ID}:circle-${CIRCLE_BUILD_NUM}"
            docker push                 "${IMAGE_ID}:circle-${CIRCLE_BUILD_NUM}"
            if [ "${CIRCLE_BRANCH}" = 'master' ]; then
              docker tag  "${IMAGE_ID}" "${IMAGE_ID}:latest"
              docker push               "${IMAGE_ID}:latest"
            fi

workflows:
  version: 2
  commit:
    jobs:
      - build
  nightly:
    jobs:
      - build
    triggers:
      - schedule:
          cron: "0 0 * * *"
          filters:
            branches:
              only:
                - master
